config/routes.rb
Rails.application.routes.draw do
  get "/artists", to: "users#index", as: :artists
  get 'users/account'
  patch 'users/update'
  devise_for :users
  root to: 'events#index'
  get "users/:id", to: "users#show", as: :profile
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  get 'about', to: 'pages#about', as: :about

  get 'search', to: 'events#search'


  resources :events do
    resources :event_attendees, only: [:create]
  end

  resources :rooms

  resources :orders, only: [:show, :create] do
    resources :payments, only: :new
  end

 resources :chatrooms, only: :show do
  resources :messages, only: :create
end


mount StripeEvent::Engine, at: '/stripe-webhooks'

end

app/models/user.rb
class User < ApplicationRecord
  has_rich_text :bio
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  validates :first_name, presence: true, length: { minimum: 2 }
  validates :last_name, presence: true, length: { minimum: 2 }
  validates :last_name, presence: true

  #PG Search
  include PgSearch::Model
  multisearchable against: [:artist_name]

  # REFERENCES
  has_one_attached :photo
  has_many :orders
  has_many :events, dependent: :destroy
  has_many :event_attendees
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/user_view.rb
class UserView < ApplicationRecord
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.where(artist: true)
  end

  def show
    @user = User.find(params[:id])
    artists = RSpotify::Artist.search(@user.artist_name)
    @artist = artists.first
  end

  def account
    @events = Event.where(user: current_user)
    @event = Event.new
  end

  def update
    @user = current_user
    @user.update(user_params)
    redirect_to users_account_path
  end

  private

  # PARAMS
  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :location, :dob, :rich_body)
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end
end

app/views/users/account.html.erb
<% content_for :chartkick do %>
                  <%= javascript_pack_tag 'chartkick' %>
                  <%= javascript_include_tag "//www.google.com/jsapi" %>
                <% end %>

<div class="container">
  <div class="row p-5">
    <div class="account-container">
      <div class="tab">
         <% if current_user.photo.attached? %>
           <%= cl_image_tag current_user.photo.key, class: "avatar-account" %>
        <% else %>
          <%= image_tag "https://icon-library.com/images/no-profile-pic-icon/no-profile-pic-icon-12.jpg", class: "avatar-account" %>
        <% end %>
        <span><%= current_user.first_name %></span>
        <br />
        <span class="menu-icon">Menu</span>
        <button class="tablinks" onclick="openCity(event, 'Account Overview')" id="defaultOpen"><i class="fas fa-user account-icon purple-background"></i> Account overview</button>
        <button class="tablinks" onclick="openCity(event, 'Tickets')"><i class="fas fa-ticket-alt account-icon blue-background"></i>Tickets</button>
        <% if current_user.artist? %>
          <button class="tablinks" onclick="openCity(event, 'Artist Details')"><i class="fas fa-music account-icon pink-background"></i>Artist Details</button>
          <button class="tablinks" onclick="openCity(event, 'Manage Events')"><i class="fas fa-cog account-icon green-background"></i>Manage Events</button>
        <% end %>
        <button class="tablinks" onclick="openCity(event, 'Edit Profile')"><i class="fas fa-edit account-icon orange-background"></i>Edit Profile</button>
       <% if current_user.artist? %>
        <button class="tablinks" onclick="openCity(event, 'New Event')"><i class="fas fa-plus-square account-icon aqua-background"></i>New Event</button>
       <% end %>
      </div>

        <div id="Account Overview" class="tabcontent">
          <div class="row p-5">
            <div class="col-md-12">
              <h2>Your Details</h2>

                <table>
                  <tr class="row-border">
                    <td class="lable">First Name: </td>
                    <td><%= current_user.first_name %></td>
                  </tr>
                  <tr class="row-border">
                    <td class="lable">Last Name:</td>
                    <td><%= current_user.last_name %></td>
                  </tr>
                  <tr class="row-border">
                    <td class="lable">Email:</td>
                    <td><%= current_user.email %></td>
                  </tr>
                  <tr class="row-border">
                    <td class="lable">Location:</td>
                    <td><%= current_user.location %></td>
                  </tr>
                  <tr class="row-border">
                    <td class="lable">DOB:</td>
                    <td><%= current_user.dob %></td>
                  </tr>
                </table>

              <div class="col-md-12 mt-5">
                <button type="button" class="btn btn-primary d-none"> <%= link_to 'Edit profile', edit_user_registration_path %> </button>
                <button type="button" class="btn btn-primary d-none"> <%= link_to 'Create event', new_event_path %> </button>
              </div>
            </div>
          </div>
        </div>

      <div id="Tickets" class="tabcontent">
          <div class="row p-5">
            <div class="col-md-12">
              <h2>My tickets</h2>
              <% if current_user.orders.any? %>

                <table>
                <tr class="row-border">
                  <th class="lable"> Event: </th>
                  <th class="lable-sm">Date: </th>
                  <th class="lable-sm">Time: </th>
                  <th class="lable-sm">Link: </th>
                </tr>

              <% current_user.orders.each do |event_attendee|  %>

                <tr class="row-border">
                  <td><%= event_attendee.event.event_name %></td>
                  <td><%= event_attendee.event.start_time.strftime('%e %B %Y') %></td>
                  <td><%= event_attendee.event.end_time.strftime('%l:%M %p') %></td>
                  <td><%= link_to 'Link', event_path(event_attendee.event) %></td>
                </tr>
                <% end %>
              </table>

              <% else %>
                <div class="w-100"><p>Your basket is empty.</p></div>
              <% end %>
          </div>
        </div>
      </div>

      <% if current_user.artist? %>
        <div id="Artist Details" class="tabcontent">
          <div class="row p-5">
            <div class="col-md-12">

                <h2>Artist Details</h2>

                <table>
                  <tr class="row-border">
                    <td class="lable-sm">Artist Name: </td>
                    <td><%= current_user.artist_name %></td>
                  </tr>
                  <tr class="row-border">
                    <td class="lable-sm">Facebook:</td>
                    <td><%= current_user.facebook %></td>
                  </tr>
                  <tr class="row-border">
                    <td class="lable-sm">Instagram:</td>
                    <td><%= current_user.instagram %></td>
                  </tr>
                  <tr class="row-border">
                    <td class="lable-sm">Youtube:</td>
                    <td><%= current_user.youtube %></td>
                  </tr>
                  <tr class="row-border">
                    <td class="lable-sm">Spotify:</td>
                    <td><%= current_user.spotify %></td>
                  </tr>
                  <tr class="row-border">
                      <td class="lable-sm">Bio: </td>
                      <td class="multi-line"><%= current_user.bio %></td>
                  </tr>
                </table>

                <div class="col-md-12 mt-5">
                  <button type="button" class="btn btn-primary d-none"> <%= link_to 'Edit profile', edit_user_registration_path %> </button>
                </div>
            </div>
          </div>
        </div>
      <% end %>

          <div id="Manage Events" class="tabcontent">
            <div class="row p-5">
              <div class="col-md-12">
                <% if current_user.artist? %>
                    <h2>My Events</h2>
                  <% @events.each_with_index do |event, index| %>

                    <div class="event-line">
                       <%= event.event_name %>
                      <div class="button-box">
                        <button  class="d-none" id="delete-button"><%= link_to 'Delete island', event_path(event), method: 'delete', data: { confirm: "Are you sure?" } %></button>
                        <button type="button" class="stats-button"> <%= link_to 'Edit event', edit_event_path(event) %> </button>
                        <button class="stats-button btn_stats" data-btn="stats_<%= event.id %>"><%= index == 0 ? "Showing" : "Show" %></button>
                      </div>
                    </div>
                  <% end %>

                  <% @events.each_with_index do |event, index| %>
                    <div class="container stats_box <%= "d-none" unless index == 0 %> " data-stats="stats_<%= event.id %>">
                      <div class="row p-3">
                        <div class="col-md-9 p-3">
                            <%= line_chart UserView.where(event_id: event).group_by_day(:created_at).count, id: "line_chart#{index}" %>
                        </div>

                        <div class="col-md-3 p-3">
                          <div class="align-middle d-flex justify-content-center align-items-center h-50 p-3 grey-border-bottom">
                            <div class="text-center">
                              <p><strong>Total Income</strong></p>
                              £<%= Money.new((event.price_cents)*(Order.where(event_id: event).count),:gbp) %>
                            </div>
                          </div>
                          <div class="align-middle d-flex justify-content-center align-items-center h-50 p-3 ">
                           <div class="text-center">
                            <p><strong>Total Sales</strong></p>
                              <%=(Order.where(event_id: event).count) %>
                            </div>
                          </div>
                        </div>
                     </div>

                      <div class="row">
                        <div class="col-md-12 p-3">
                          <%= geo_chart UserView.where(event_id: event).group(:country).count, id: "map_chart#{index}"  %>
                        </div>
                      </div>

                    </div>
                  <% end %>
                <% end %>

              </div>
            </div>
          </div>

          <div id="Edit Profile" class="tabcontent">
            <div class="row p-5">
              <div class="col-md-12">
                <h2>Edit Profile</h2>
                <%= simple_form_for current_user, url: users_update_path, method: :patch do |f| %>
                    <%= f.input :first_name, required: true, autofocus: true,  error: 'Your name is required'  %>
                    <%= f.input :last_name, required: true %>
                    <%= f.input :email %>
                    <%= f.input :location %>
                    <%= f.input :dob %>
                    <% if current_user.artist? %>
                    <%= f.input :artist_name %>
                    <%= f.rich_text_area :bio %>
                    <%= f.input :bank_details %>
                    <%= f.input :facebook %>
                    <%= f.input :instagram %>
                    <%= f.input :youtube %>
                    <% end %>
                    <%= f.submit 'Add your Event', class: 'btn btn-primary d-none' %>
                <% end %>
              </div>
            </div>
          </div>

         <% if current_user.artist? %>
          <div id="New Event" class="tabcontent">
            <div>
              <%= render "/events/partial/new" %>
            </div>
          </div>
        <% end %>

    </div>
  </div>
</div>

  <script>
  function openCity(evt, cityName) {
    var i, tabcontent, tablinks;
    tabcontent = document.getElementsByClassName("tabcontent");
    for (i = 0; i < tabcontent.length; i++) {
      tabcontent[i].style.display = "none";
    }
    tablinks = document.getElementsByClassName("tablinks");
    for (i = 0; i < tablinks.length; i++) {
      tablinks[i].className = tablinks[i].className.replace(" active", "");
    }
    document.getElementById(cityName).style.display = "block";
    evt.currentTarget.className += " active";
  }

  // Get the element with id="defaultOpen" and click on it
  document.getElementById("defaultOpen").click();
  </script>

<script>
  const buttons = document.querySelectorAll(".btn_stats");
    const boxs = document.querySelectorAll(".stats_box");


  buttons.forEach((button) => {
    button.addEventListener("click", (event) => {
      boxs.forEach((box) => {
        if (button.dataset.btn === box.dataset.stats) {
          buttons.forEach(button => button.innerText = "Show");
          event.target.innerText = "Showing"
          box.classList.add("d-block")
          box.classList.remove("d-none")
        } else {
          box.classList.remove("d-block")
          box.classList.add("d-none")
        }
      })
    })
  })
  </script>

  <script>
    Chartkick.eachChart( function(chart) {
    chart.redraw();
    });
  </script>

app/views/users/index.html.erb
index.html.erb

<% @users.each do |user| %>
  <%= link_to user.artist_name, profile_path(user)  %>
<% end %>

app/views/users/show.html.erb
<div class="container">

<div class="artist-flex">
<div class="flex-top-a">
<%# <% if @user.photo.attached? %>
  <%= cl_image_tag @user.photo.key, class: "avatar-artist" %>
<div class="social-list">
<p class="follow-icons">
<a href="<%= @user.instagram %>" target="_blank">

<i class="fab fa-instagram"></i></a>
    <a href="<%= @user.facebook %>" target="_blank">
<i class="fab fa-facebook"></i>
</a>
<a href="<%= @user.spotify %>" target="_blank">
<i class="fab fa-spotify"></i></a>

</p>
</div> 

<%# <% else
  <%= image_tag "https://icon-library.com/images/no-profile-pic-icon/no-profile-pic-icon-12.jpg", class: "avatar_account" %>
<%# <% end %> 
</div>

<div class="flex-bottom-a">
<h1><%= @user.artist_name %></h1>
  <br />
  <p><%= @user.bio %></p>

</div>
</div>

<% if @artist %>
<iframe src="https://open.spotify.com/embed/<%= @artist.external_urls['spotify'].split("/")[-2..-1].join("/") %>" width="500" height="300" frameborder="0" allowtransparency="true" allow="encrypted-media"></iframe>

<% end %>

<iframe width="500" height="300" src="<%= @user.youtube %>" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen></iframe>

</br>
<h3>Upcoming Events</h3>

<div class="row">
    <% @user.events.each do |event| %>
    <%= link_to event_path(event) do %>
      <div class="col-4">
        <div class="event-card">
          <% if event.photo.attached? %>
            <div class="event-card-image" style="height: 150px; background-image: url('<%= cl_image_path event.photo.key %>')"></div>
          <% else %>
             <div class="event-card-image" style="height: 150px; background-image: url(<%= 'https://static.billboard.com/files/2020/12/chloe-x-halle-tiny-desk-2020-billboard-1548-1607458577-compressed.jpg' %>)"></div>
          <% end %>
          <div class="event-card-content">
            <div class="event-card-title">
              <h4><%= event.event_name %></h4>
            <p>Hosted by <%= event.user.first_name %></p>
             </div>
              <div class="flex">
                <%= event.city %> | <%= event.start_time.strftime('%A, %b %d') %> | <%= event.start_time.strftime('%l:%M %p') %>
              </div>
            <div class="genre-box">
                <% event.genres.each do |genre| %>
                <span class="mr-2" ><%= genre.name %> </span>
              <% end %>
            </div>
          </div>
        </div>
      </div>
      <% end %>
    <% end %>
  </div>

</div>