config/routes.rb
Rails.application.routes.draw do
  get "/artists", to: "users#index", as: :artists
  get 'users/account'
  patch 'users/update'
  devise_for :users
  root to: 'events#index'
  get "users/:id", to: "users#show", as: :profile
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  get 'about', to: 'pages#about', as: :about

  get 'search', to: 'events#search'


  resources :events do
    resources :event_attendees, only: [:create]
  end

  resources :rooms

  resources :orders, only: [:show, :create] do
    resources :payments, only: :new
  end

 resources :chatrooms, only: :show do
  resources :messages, only: :create
end


mount StripeEvent::Engine, at: '/stripe-webhooks'

end

app/views/shared/_banner.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.5),rgba(0,0,0,0.5)), url(https://res.cloudinary.com/ddqpdj02o/image/upload/v1614936112/Copy_of_Untitled_ro8o6o.png);">
  <div class="container">
    <h1>Live from your living room</h1>
    <p>Your ticket to the world of global music</p>
  </div>
</div>

app/views/shared/_bannersm.html.erb
<div class="banner-small" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://diymusician.cdbaby.com/wp-content/uploads/2016/12/studio-image-diy-blog.jpeg);">
  <div class="container">
    <h1>Live from your living room</h1>
    <p>Your ticket to the world of global music</p>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
<div class="footer-copyright">
    <p><%= image_tag "https://res.cloudinary.com/ddqpdj02o/image/upload/v1614705819/Stand_Up_Comedy_10_j2mygu.png" %> Front<strong>Row</strong> 2021</p>
  </div>
  <div class="footer-links">
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-spotify"></i></a>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon sticky">
  <%= link_to events_path, class: "navbar-brand" do %>
    <p>Front<strong>Row</strong><%= image_tag "https://res.cloudinary.com/ddqpdj02o/image/upload/v1614705778/Stand_Up_Comedy_9_mpuvgr.png" %></p>
    <% end %>
    
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item">
          <%= link_to "About", about_path, class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <% if current_user.photo.attached? %>
            <%= cl_image_tag current_user.photo.key, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false  %>
          <% else %>
            <%= image_tag "https://icon-library.com/images/no-profile-pic-icon/no-profile-pic-icon-12.jpg", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <% end %>
          <div class="dropdown-menu dropdown-menu-right dropdown-background dropdown-border" aria-labelledby="navbarDropdown">
            <%= link_to "My Account", users_account_path(current_user), class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/shared/_search.html.erb
<!-- Button trigger modal -->
<button type="button" id="search-button" data-toggle="modal" data-target="#exampleModal">
  <i class="fas fa-search fa-lg"></i>
</button>

<!-- Modal -->
<div class="modal fade" data-controller="search" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true" data-backdrop="keyboard mouse">
  <div class="modal-dialog modal-xl">
    <div class="modal-content">
      <div class="modal-header">
        <div class="form-field">
          <%= form_tag search_path, method: :get do %>
            <%= text_field_tag :query,
              params[:query],
              id: "form-field",
              placeholder: "Find an artist, event or genre...",
              data: { search_target: "input", action: "keyup->search#searchResults" }
            %>
          <% end %>
        </div>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body", data-search-target="container">
        <%#= render 'events/search', artists: @artists, events: @events, genres: @genres %>
      </div>
    </div>
  </div>
</div>