config/routes.rb
Rails.application.routes.draw do
  get "/artists", to: "users#index", as: :artists
  get 'users/account'
  patch 'users/update'
  devise_for :users
  root to: 'events#index'
  get "users/:id", to: "users#show", as: :profile
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  get 'about', to: 'pages#about', as: :about

  get 'search', to: 'events#search'


  resources :events do
    resources :event_attendees, only: [:create]
  end

  resources :rooms

  resources :orders, only: [:show, :create] do
    resources :payments, only: :new
  end

 resources :chatrooms, only: :show do
  resources :messages, only: :create
end


mount StripeEvent::Engine, at: '/stripe-webhooks'

end

app/models/event.rb
class Event < ApplicationRecord
  has_rich_text :description

  # PG Search
  include PgSearch::Model
  multisearchable against: [:event_name, :city, :country]

  after_create :set_sku
  after_create :create_room
  has_one :room
  # CLOUDINARY
  has_one_attached :photo
  # REFERENCES
  has_many :event_attendees
  has_many :users, through: :event_attendees
  belongs_to :user
  has_many :event_genres, dependent: :destroy
  has_many :genres, through: :event_genres
  # VALIDATIONS
  validates :event_name, presence: true
  validates :description, presence: true
  validates :start_time, presence: true
  validates :end_time, presence: true
  validates :city, presence: true
  validates :country, presence: true
  # STRIPE
  monetize :price_cents

  def set_sku
    self.sku = "#{self.id}  #{self.event_name.gsub(" ", "-")}"
    self.save
  end

  def create_room
    Room.create(name: event_name, event: self)
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  skip_before_action :authenticate_user!, only: %i[index show search]

  def index
    # Add query when implementing search bar
    if params[:query].present?
      @events = Event.select { |event| event.genres.include?(Genre.find_by(name: params[:query])) }
    elsif params[:country].present?
      @events = Event.where(country: params[:country])
    elsif params[:city].present?
      @events = Event.where(city: params[:city])
    else
      @events = Event.all
    end
    @search = params[:search]
    @query = params[:query] || params[:city] || params[:country]
      # @events = Event.all
  end

  # NEW
  def new
    @event = Event.new
  end

  # SHOW
  def show
    @event = Event.find(params[:id])
    # UserVisit.visit(request.remote_ip, Event.find(params[:id]), "show")
  end

  # CREATE
  def create
    @event = Event.new(event_params)
    @event_genre = params[:event][:genre_ids].reject(&:blank?)
    @event.user = current_user
    @event.price_cents = @event.price_cents * 100
    if @event.save
      @event_genre.each do |genre|
        EventGenre.create!(
          event_id: @event.id,
          genre_id: genre.to_i
        )
      end
      Chatroom.create(room_id: @event.room.id)
      redirect_to event_path(@event)
    else
      render :new
    end
  end

  # DESTROY
  def destroy
    @event = Event.find(params[:id])
    @event.destroy
    redirect_to events_path
  end

  # UPDATE
  def update
    @event = Event.find(params[:id])
    if @event.update(event_params)
      redirect_to event_path(@event)
    else
      render :edit
    end
  end

  def edit
    @event = Event.find(params[:id])
  end

  def search
    if params[:query].present?
      # @events = Event.where("event_name ILIKE ?", "%#{params[:query]}%")
      @artists = PgSearch.multisearch(params[:query]).where(searchable_type: 'User')
      @events = PgSearch.multisearch(params[:query]).where(searchable_type: 'Event')
      @genres = PgSearch.multisearch(params[:query]).where(searchable_type: 'Genre')
      # elsif params[:query].empty?
      #   alert()
    else
      @events = Event.all
    end
    respond_to do |format|
      format.html { render partial: 'events/search', locals: { artists: @artists, events: @events, genres: @genres } }
    end
  end

  private

  # PARAMS

  def event_params
    params.require(:event).permit(:event_name, :description, :price_cents, :start_time, :end_time, :city, :country, :photo)
  end
end

app/views/events/_img_form.html.erb
<%= simple_form_for(@event) do |f| %>
  <%= f.input :photo, as: :file %>
<% end %>

app/views/events/_search.html.erb
<div class="container">
  <% if params[:query].present? %>

    <% if artists.empty? && events.empty? && genres.empty? %>
      <h1 class="results-search"><%= 'No results found...'%></h1>
    <% else %>
      <div class="row justify-content-between">
      <% unless artists.empty? %>
        <div class="col-md-6">
          <div class="sorted-table mb-4" id="event-artist">
            
              <h3 class="mb-3">Artists</h3>
                <ul>
                  <% artists.each do |artist| %>
                    <li class="mb-3"><%= cl_image_tag artist.searchable_type.constantize.find(artist.searchable_id).photo.key, class: "avatar-search mr-3" %><%= link_to "#{artist.searchable_type.constantize.find(artist.searchable_id).artist_name}", profile_path(artist.searchable_id) %></li>
                  <% end %>
                </ul>
          </div>
        </div>
      <% end %>

      <% unless events.empty? %>
        <div class="col-md-6">
          <div class="sorted-table mb-4" id="event-event">
              <h3 class="mb-3">Events</h3>
                <ul>
                  <% events.each do |event| %>
                    <li class="mb-3"><%= cl_image_tag event.searchable_type.constantize.find(event.searchable_id).photo.key, class: "avatar-search mr-3" %><%= link_to "#{event.searchable_type.constantize.find(event.searchable_id).event_name}", event_path(event.searchable_id) %></li>
                  <% end %>
                </ul>
          </div>
        </div>
      <% end %>

      <% unless genres.empty? %>
        <div class="col-md-6">
          <div class="sorted-table mb-4" id="event-genre">
              <h3 class="mb-3">Genres</h3>
                <ul>
                  <% genres.each do |genre| %>
                    <li class="mb-3"><%= image_tag "genre.png", class: "avatar-search mr-3" %><%= link_to "#{genre.searchable_type.constantize.find(genre.searchable_id).name}", events_path(query: genre.searchable_type.constantize.find(genre.searchable_id).name, search: true) %></li>
                  <% end %>
                </ul>
          </div>
        </div>
      <% end %>
      
      <% unless events.empty? %>
        <div class="col-md-6">
          <div class="sorted-table mb-4" id="event-genre">
              <h3 class="mb-3">Countries</h3>
                <ul>
                  <% events.each do |event| %>
                    <li class="mb-3"><%= image_tag "globe.png", class: "avatar-search mr-3" %><%= link_to "#{event.searchable_type.constantize.find(event.searchable_id).country}", events_path(country: event.searchable_type.constantize.find(event.searchable_id).country, search: true) %></li>
                  <% end %>
                </ul>
          </div>
        </div>
      <% end %>

      <% unless events.empty? %>
        <div class="col-md-6">
          <div class="sorted-table mb-4" id="event-genre">
            <h3 class="mb-3">Cities</h3>
              <ul>
                <% events.each do |event| %>
                  <li class="mb-3"><%= image_tag "city.png", class: "avatar-search mr-3" %><%= link_to "#{event.searchable_type.constantize.find(event.searchable_id).city}", events_path(city: event.searchable_type.constantize.find(event.searchable_id).city, search: true) %></li>
                <% end %>
              </ul>
          </div>
        </div>
      <% end %>
      </div>
    <% end %>
  <% end %>
</div>

app/views/events/edit.html.erb
<div class="banner-small" style="background-image: linear-gradient(rgba(0,0,0,0.6),rgba(0,0,0,0.4)), url(https://diymusician.cdbaby.com/wp-content/uploads/2016/12/studio-image-diy-blog.jpeg);">
  <div class="container">
    <h1>Update your event</h1>
  </div>
</div>

<div class="container rounded" style="width: 900px;">
  <div class="row justify-content-center">
    <div class="col-md-8">
      <%= simple_form_for (@event) do |f| %>
        <%= f.input :event_name, input_html: { class: "nice-class", maxlength: 50 } %>
        <%= f.label :Description %>
        <%= f.rich_text_area :description, input_html: { maxlength: 150 } %>
        <%= f.input :start_time, as: :string, required: true, input_html: {class: "datepicker"} %>
        <%= f.input :end_time, as: :string, required: true, input_html: {class: "datepicker"} %>
        <%= f.input :city %>
        <%= f.country_select :country, priority_countries: ["GB", "US"] %>
        <%= f.input :price_cents, label: "Price per Ticket" %>
        <%= f.association :genres, multiple: true, size: 3 %>
        <%= f.input :photo, as: :file %>
        <%= f.submit 'Add your Event', class: 'btn btn-primary' %>
      <% end %>
    </div>
  </div>
 </div>

app/views/events/index.html.erb
<% if @search %>
  <div class="banner-small" style="background-image: linear-gradient(60deg, #303030 0%, #181818 100%);">
    <div class="container">
      <h1><strong>SEARCH RESULTS</strong></h1>
      <h1 id="search-result">'<%= @query %>'</h1>
    </div>
  </div>
  <div class="container">
    <h3>Upcoming Events</h3>
    <p>You searched for '<%= @query %>'. Displaying <%= @events.count %> events.</p>
    <div class="row">
      <% @events.each do |event| %>
        <%= link_to event_path(event) do %>
          <div class="col-4">
            <div class="event-card">
              <% if event.photo.attached? %>
                <div class="event-card-image" style="background-image: url('<%= cl_image_path event.photo.key %>')"></div>
              <% else %>
                <div class="event-card-image" style="background-image: url(<%= 'https://static.billboard.com/files/2020/12/chloe-x-halle-tiny-desk-2020-billboard-1548-1607458577-compressed.jpg' %>)"></div>
              <% end %>
              <div class="event-card-content">
                <div class="event-card-title">
                  <h4><%= event.event_name %></h4>
                  <p>Hosted by <%= event.user.artist_name %></p>
                </div>
                <div class="flex">
                  <%= event.country %>  |  <%= event.start_time.strftime('%e %B %Y') %>  |  <%= event.start_time.strftime('%l:%M %p') %>
                </div>
                <%# <p>£<%= Money.new(event.price_cents.to_s, :gbp) %>
                <div class="genre-box">
                  <% event.genres.each do |genre| %>
                    <span class="mr-2" ><%= genre.name %> </span>
                  <% end %>
                </div>
              </div>
            </div>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>
<% else %>
  <%= render 'shared/banner' %>
  <div class="container">
    <h3>Upcoming Events</h3>
    <p>Displaying <%= @events.count %> events.</p>
    <div class="row">
      <% @events.each do |event| %>
        <%= link_to event_path(event) do %>
          <div class="col-4">
            <div class="event-card">
              <% if event.photo.attached? %>
                <div class="event-card-image" style="background-image: url('<%= cl_image_path event.photo.key %>')"></div>
              <% else %>
                <div class="event-card-image" style="background-image: url(<%= 'https://static.billboard.com/files/2020/12/chloe-x-halle-tiny-desk-2020-billboard-1548-1607458577-compressed.jpg' %>)"></div>
              <% end %>
              <div class="event-card-content">
                <div class="event-card-title">
                  <h4><%= event.event_name %></h4>
                  <p>Hosted by <%= event.user.artist_name %></p>
                </div>
                <div class="flex">
                  <%= event.country %>  |  <%= event.start_time.strftime('%e %B %Y') %>  |  <%= event.start_time.strftime('%l:%M %p') %>
                </div>
                <%# <p>£<%= Money.new(event.price_cents.to_s, :gbp) %>
                <div class="genre-box">
                  <% event.genres.each do |genre| %>
                    <span class="mr-2" ><%= genre.name %> </span>
                  <% end %>
                </div>
              </div>
            </div>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>
<% end %>

app/views/events/new.html.erb
<div class="banner-small" style="background-image: linear-gradient(rgba(0,0,0,0.6),rgba(0,0,0,0.4)), url(https://diymusician.cdbaby.com/wp-content/uploads/2016/12/studio-image-diy-blog.jpeg);">
  <div class="container">
    <h1>Create a new event</h1>
  </div>
</div>

<div class="container rounded" style="width: 900px;">
  <div class="row justify-content-center">
    <div class="col-md-8">
      <%= simple_form_for (@event) do |f| %>
        <%= f.input :event_name, input_html: { class: "nice-class", maxlength: 50 } %>
        <%= f.label :Description %>
        <%= f.rich_text_area :description, input_html: { maxlength: 150 } %>
        <%= f.input :start_time, as: :string, required: true, input_html: {class: "datepicker"} %>
        <%= f.input :end_time, as: :string, required: true, input_html: {class: "datepicker"} %>
        <%= f.input :city %>
        <%= f.country_select :country, priority_countries: ["GB", "US"] %>
        <%= f.input :price_cents, label: "Price per Ticket in £" %>
        <%= f.association :genres, multiple: true, size: 3, input_html: { class: 'select2'}, label: "Select your Genre" %>
        <%= f.input :photo, as: :file %>
        <%= f.submit 'Add your Event', class: 'btn btn-primary' %>
      <% end %>
    </div>
  </div>
 </div>

app/views/events/search.html.erb
<div class="container">
  <% if @artists.nil? && @events.nil? && @genres.nil? %>
    <h1 class="results-search"><%= 'No results found...'%></h1>
  <% else %>
    <div class="row">
      <div class="col-md-6">
        <div class="sorted-table" id="event-artist">
          <% unless @artists.empty? %>
            <h3>Artists</h3>
              <hr>
              <ul>
                <% @artists.each do |artist| %>
                  <li><%= link_to "#{artist.searchable_type.constantize.find(artist.searchable_id).artist_name}", profile_path(artist.searchable_id) %></li>
                <% end %>
              </ul>
          <% end %>
        </div>
      </div>
    
      <div class="col-md-6">
        <div class="sorted-table" id="event-event">
          <% unless @events.empty? %>
            <h3>Events</h3>
              <hr>
              <ul>
                <% @events.each do |event| %>
                  <li><%= link_to "#{event.searchable_type.constantize.find(event.searchable_id).event_name}", event_path(event.searchable_id) %></li>
                <% end %>
              </ul>
            <% end %>
         </div>
      </div>
    </div>

    <div class="row">
      <div class="col-md-6">
        <div class="sorted-table" id="event-genre">
          <% unless @genres.empty? %>
            <h3>Genres</h3>
              <hr>
              <ul>
                <% @genres.each do |genre| %>
                  <li><%= link_to "#{genre.searchable_type.constantize.find(genre.searchable_id).name}", events_path(query: genre.searchable_type.constantize.find(genre.searchable_id).name, search: true) %></li>
                <% end %>
              </ul>
            <% end %>
         </div>
      </div>

      <div class="col-md-6">
        <div class="sorted-table" id="event-genre">
          <% unless @events.empty? %>
            <h3>Countries</h3>
            <hr>
              <ul>
                <% @events.each do |event| %>
                  <li><%= link_to "#{event.searchable_type.constantize.find(event.searchable_id).country}", events_path(country: event.searchable_type.constantize.find(event.searchable_id).country) %></li>
                <% end %>
              </ul>
          <% end %>
        </div>
      </div>
    </div>
    
    <div class="row">
      <div class="col-md-6">
        <div class="sorted-table" id="event-genre">
          <% unless @events.empty? %>
          <h3>Cities</h3>
            <hr>
            <ul>
              <% @events.each do |event| %>
                <li><%= link_to "#{event.searchable_type.constantize.find(event.searchable_id).city}", events_path(city: event.searchable_type.constantize.find(event.searchable_id).city) %></li>
              <% end %>
            </ul>
          <% end %>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/events/show.html.erb
<% if @event.photo.attached? %>
  <div class="banner-event" style="background-image: linear-gradient(rgba(0,0,0,0.2),rgba(0,0,0,0.3)), url('<%= cl_image_path @event.photo.key %>');">
  <div class="container" id="event-header" >
    <h1><%= @event.user.artist_name %></h1>
    <h2><%= @event.start_time.strftime('%e %B %Y') %></h2>
  </div>
</div>
      <% else %>
        <div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.2),rgba(0,0,0,0.3)), url('https://res.cloudinary.com/soundbetter/image/upload/c_fill,f_auto,g_face:auto,h_288,q_90,w_540/v1610559632/assets/photos/55969/IMG_3093.jpg');">
  <div class="container">
        <h1><%= @event.user.artist_name %></h1>
    <h2><%= @event.start_time.strftime('%A, %b %d') %></h2>
  </div>
</div>
<% end %>

<div class ="container">

<div class ="body-flex">

<div class="flex-left">

<h1><%= @event.event_name %></h1>
<br>
<h5><%= cl_image_tag @event.user.photo.key, class: "avatar-event" %>Hosted by <%= link_to @event.user.artist_name, profile_path(@event.user_id) %></h5>
</br>
<h4>Event Description</h4>

<p><%= @event.description %></p>
</br>
<h4>About the artist</h4>


<p><%= @event.user.bio %></p>

</div>

<div class="flex-right">

<p><%= @event.city %>, <%= @event.country %></p>

<p><%= @event.start_time.strftime('%A, %b %d') %></p>

<p><%= @event.start_time.strftime('%l:%M %p') %></p>

<p>£<%= Money.new(@event.price_cents.to_s, :gbp) %></p>

<p style="color:gray">Please note: all events are currently available to stream worldwide</p>

</br>
  <% if Order.where(event: @event, state: 'paid', user: current_user).any? %>
    <%= link_to "Go to stream", room_path(@event.room), class: 'btn btn-primary' %>
    <% elsif @event.user == current_user %>
    <%= link_to "Start Stream", room_path(@event.room), class: 'btn btn-primary' %>
    <% else %>
    <%= form_tag orders_path do %>
    <%= hidden_field_tag 'event_id', @event.id %>
    <%= submit_tag 'Buy Ticket', class: 'btn btn-primary' %>
    <% end %>
 <% end %>

</div>
</div>
</div>